### ISSUE TITLE
do you retrain mtcnn?

### ISSUE THREAD

**Issue by Cv9527** [blankWorld/MTCNN-caffe#1]
Since the onet is half of source mtcnn, do you retrain mtcnn?

**Comment by blankWorld** [comment]
yes, i  shrinked o-net model by reducing it to half  parameters and retrain it

**Comment by sfzhoujob** [comment]
could you share the training code?

**Comment by blankWorld** [comment]
I m so sorry that training code is so messy that it will take me very much time to put it in order. recently, I m busy in my work and have little time to pack the training code.
I suggest you should train your model in a bootstrap manner and shrink the model by picking kernels which have the top N L1 norm values and fine-tune it

**Comment by billtiger** [comment]
how to build this project? @Cv9527
