### ISSUE TITLE
Just three models

### ISSUE THREAD

**Issue by luuuyi** [blankWorld/MTCNN-caffe#2]
hello, i m new to mtcnn.
I noted that the origin version has four [models(),](https://github.com/kpzhang93/MTCNN_face_detection_alignment/tree/master/code/codes) the last one is named L-net. I guess L-net is used to generate five points on the face(face alignment). But in your repo you just have three models and show some pictures have landmarks. So, my question is, without L-net also can generate five points?

**Comment by blankWorld** [comment]
Hello, L-net is used to refine o-net's key point predictions.This project is three stage cascade detection without L-net.
