### ISSUE TITLE
differences between your model and original model

### ISSUE THREAD

**Issue by lbwang2006** [blankWorld/MTCNN-caffe#3]
The author's original model is fed into RGB image, and is stored as colomn- first, what about your model?

**Comment by blankWorld** [comment]
The author's is from matlab and re-implemented in c++. This model's is retrained by me. Its input is BGR and stored in row-major order.Please  see mtcnn.cpp in detail.

**Comment by billtiger** [comment]
how to build this project? @lbwang2006

**Comment by lbwang2006** [comment]
@billtiger sorry, I did not build this project, I only want to transfer this model to original mtcnn model.
